### ISSUE TITLE
error while running import_vdj

### ISSUE THREAD

**Issue by gt7901b** [rnabioco/djvdj#84]
HI, 

I ran the following to add BCR data but got the both TCR and BCR chains are present error.  But the input is only a BCR file. 
Will you please let me know how to solve this?

Thanks
 
bcr_added=import_vdj(
input=seurat_obj,
    vdj_dir = "BCR_data/sample_data/",
  )

Error in .f(.x[[i]], ...): Malformed input data, both TCR and BCR chains are present.

**Comment by sheridar** [comment]
Hi, this is tricky to troubleshoot without seeing the input data. Would you be willing to send the filtered_contig_annotations.csv file produced by cellranger? You can attach this to your comment, or you can email it to me here: ryan.sheridan@cuanschutz.edu

**Comment by gt7901b** [comment]
[filtered_contig_annotations02.csv](https://github.com/rnabioco/djvdj/files/7530217/filtered_contig_annotations02.csv)

@sheridar  Thanks for your quick response. The 10x output of BCR attached.

**Comment by sheridar** [comment]
The reason you are seeing this error is because there is a small number of TCR contigs present in your input data (these are mostly low quality annotations).

To account for this situation, I'm going to modify `import_vdj` so it returns a warning instead of an error when both BCR and TCR data are present in the input file. This will allow the function to work with your data, I'll let you know when this is complete

**Comment by sheridar** [comment]
This should be corrected with bcd7f56ddf6bfa5837314e949af8f7fb5f024993, please reopen if you still have issues
